//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitCoin.FatToAccM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="GDS_HUB", ConfigurationName="FatToAccM.IFatC_to_AccM", CallbackContract=typeof(BitCoin.FatToAccM.IFatC_to_AccMCallback))]
    public interface IFatC_to_AccM {
        
        [System.ServiceModel.OperationContractAttribute(Action="GDS_HUB/IFatC_to_AccM/logIn", ReplyAction="GDS_HUB/IFatC_to_AccM/logInResponse")]
        int logIn(string accountName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="GDS_HUB/IFatC_to_AccM/logIn", ReplyAction="GDS_HUB/IFatC_to_AccM/logInResponse")]
        System.Threading.Tasks.Task<int> logInAsync(string accountName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="GDS_HUB/IFatC_to_AccM/logOut", ReplyAction="GDS_HUB/IFatC_to_AccM/logOutResponse")]
        bool logOut();
        
        [System.ServiceModel.OperationContractAttribute(Action="GDS_HUB/IFatC_to_AccM/logOut", ReplyAction="GDS_HUB/IFatC_to_AccM/logOutResponse")]
        System.Threading.Tasks.Task<bool> logOutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="GDS_HUB/IFatC_to_AccM/register", ReplyAction="GDS_HUB/IFatC_to_AccM/registerResponse")]
        bool register(long userId, string userName, string passWord, string firstName, string lastName, string email, string joinDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="GDS_HUB/IFatC_to_AccM/register", ReplyAction="GDS_HUB/IFatC_to_AccM/registerResponse")]
        System.Threading.Tasks.Task<bool> registerAsync(long userId, string userName, string passWord, string firstName, string lastName, string email, string joinDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="GDS_HUB/IFatC_to_AccM/sendTransaction", ReplyAction="GDS_HUB/IFatC_to_AccM/sendTransactionResponse")]
        bool sendTransaction(string userAccount, string account, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="GDS_HUB/IFatC_to_AccM/sendTransaction", ReplyAction="GDS_HUB/IFatC_to_AccM/sendTransactionResponse")]
        System.Threading.Tasks.Task<bool> sendTransactionAsync(string userAccount, string account, int amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFatC_to_AccMCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="GDS_HUB/IFatC_to_AccM/confirmation")]
        void confirmation();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="GDS_HUB/IFatC_to_AccM/serverInfo")]
        void serverInfo(string info);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFatC_to_AccMChannel : BitCoin.FatToAccM.IFatC_to_AccM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FatC_to_AccMClient : System.ServiceModel.DuplexClientBase<BitCoin.FatToAccM.IFatC_to_AccM>, BitCoin.FatToAccM.IFatC_to_AccM {
        
        public FatC_to_AccMClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public FatC_to_AccMClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public FatC_to_AccMClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FatC_to_AccMClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FatC_to_AccMClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int logIn(string accountName, string password) {
            return base.Channel.logIn(accountName, password);
        }
        
        public System.Threading.Tasks.Task<int> logInAsync(string accountName, string password) {
            return base.Channel.logInAsync(accountName, password);
        }
        
        public bool logOut() {
            return base.Channel.logOut();
        }
        
        public System.Threading.Tasks.Task<bool> logOutAsync() {
            return base.Channel.logOutAsync();
        }
        
        public bool register(long userId, string userName, string passWord, string firstName, string lastName, string email, string joinDate) {
            return base.Channel.register(userId, userName, passWord, firstName, lastName, email, joinDate);
        }
        
        public System.Threading.Tasks.Task<bool> registerAsync(long userId, string userName, string passWord, string firstName, string lastName, string email, string joinDate) {
            return base.Channel.registerAsync(userId, userName, passWord, firstName, lastName, email, joinDate);
        }
        
        public bool sendTransaction(string userAccount, string account, int amount) {
            return base.Channel.sendTransaction(userAccount, account, amount);
        }
        
        public System.Threading.Tasks.Task<bool> sendTransactionAsync(string userAccount, string account, int amount) {
            return base.Channel.sendTransactionAsync(userAccount, account, amount);
        }
    }
}
