//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BitCoin
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GDS_databaseContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GDS_databaseContainer object using the connection string found in the 'GDS_databaseContainer' section of the application configuration file.
        /// </summary>
        public GDS_databaseContainer() : base("name=GDS_databaseContainer", "GDS_databaseContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GDS_databaseContainer object.
        /// </summary>
        public GDS_databaseContainer(string connectionString) : base(connectionString, "GDS_databaseContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GDS_databaseContainer object.
        /// </summary>
        public GDS_databaseContainer(EntityConnection connection) : base(connection, "GDS_databaseContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
