//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdsHub.ServiceReferenceTransaction {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTransaction.ITransaction", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ITransaction {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaction/addNewTransaction", ReplyAction="http://tempuri.org/ITransaction/addNewTransactionResponse")]
        bool addNewTransaction(long userId, string transTime, string transType, string coinType, decimal amount, string add);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaction/addNewTransaction", ReplyAction="http://tempuri.org/ITransaction/addNewTransactionResponse")]
        System.Threading.Tasks.Task<bool> addNewTransactionAsync(long userId, string transTime, string transType, string coinType, decimal amount, string add);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaction/getTransInfo", ReplyAction="http://tempuri.org/ITransaction/getTransInfoResponse")]
        string[] getTransInfo(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaction/getTransInfo", ReplyAction="http://tempuri.org/ITransaction/getTransInfoResponse")]
        System.Threading.Tasks.Task<string[]> getTransInfoAsync(long userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransactionChannel : GdsHub.ServiceReferenceTransaction.ITransaction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionClient : System.ServiceModel.ClientBase<GdsHub.ServiceReferenceTransaction.ITransaction>, GdsHub.ServiceReferenceTransaction.ITransaction {
        
        public TransactionClient() {
        }
        
        public TransactionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool addNewTransaction(long userId, string transTime, string transType, string coinType, decimal amount, string add) {
            return base.Channel.addNewTransaction(userId, transTime, transType, coinType, amount, add);
        }
        
        public System.Threading.Tasks.Task<bool> addNewTransactionAsync(long userId, string transTime, string transType, string coinType, decimal amount, string add) {
            return base.Channel.addNewTransactionAsync(userId, transTime, transType, coinType, amount, add);
        }
        
        public string[] getTransInfo(long userId) {
            return base.Channel.getTransInfo(userId);
        }
        
        public System.Threading.Tasks.Task<string[]> getTransInfoAsync(long userId) {
            return base.Channel.getTransInfoAsync(userId);
        }
    }
}
