//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gds_hub.ServiceReferenceCPortal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCPortal.IPortal", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IPortal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/checkIsExistedUserName", ReplyAction="http://tempuri.org/IPortal/checkIsExistedUserNameResponse")]
        bool checkIsExistedUserName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/checkIsExistedUserName", ReplyAction="http://tempuri.org/IPortal/checkIsExistedUserNameResponse")]
        System.Threading.Tasks.Task<bool> checkIsExistedUserNameAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/addNewUser", ReplyAction="http://tempuri.org/IPortal/addNewUserResponse")]
        bool addNewUser(string userName, string passWord, string firstName, string lastName, string email, string joinDate, string lastLoginTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/addNewUser", ReplyAction="http://tempuri.org/IPortal/addNewUserResponse")]
        System.Threading.Tasks.Task<bool> addNewUserAsync(string userName, string passWord, string firstName, string lastName, string email, string joinDate, string lastLoginTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPortalChannel : gds_hub.ServiceReferenceCPortal.IPortal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortalClient : System.ServiceModel.ClientBase<gds_hub.ServiceReferenceCPortal.IPortal>, gds_hub.ServiceReferenceCPortal.IPortal {
        
        public PortalClient() {
        }
        
        public PortalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PortalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool checkIsExistedUserName(string userName) {
            return base.Channel.checkIsExistedUserName(userName);
        }
        
        public System.Threading.Tasks.Task<bool> checkIsExistedUserNameAsync(string userName) {
            return base.Channel.checkIsExistedUserNameAsync(userName);
        }
        
        public bool addNewUser(string userName, string passWord, string firstName, string lastName, string email, string joinDate, string lastLoginTime) {
            return base.Channel.addNewUser(userName, passWord, firstName, lastName, email, joinDate, lastLoginTime);
        }
        
        public System.Threading.Tasks.Task<bool> addNewUserAsync(string userName, string passWord, string firstName, string lastName, string email, string joinDate, string lastLoginTime) {
            return base.Channel.addNewUserAsync(userName, passWord, firstName, lastName, email, joinDate, lastLoginTime);
        }
    }
}
