//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseHUB.ServiceReferenceMDB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMDB.IMDB")]
    public interface IMDB {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/getLastestExistedUserId", ReplyAction="http://tempuri.org/IMDB/getLastestExistedUserIdResponse")]
        long getLastestExistedUserId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/getLastestExistedUserId", ReplyAction="http://tempuri.org/IMDB/getLastestExistedUserIdResponse")]
        System.Threading.Tasks.Task<long> getLastestExistedUserIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/registerAsUser", ReplyAction="http://tempuri.org/IMDB/registerAsUserResponse")]
        void registerAsUser(long usrId, string userName, string firstName, string lastName, string joinDate, string passWord, string eMail, string lastLoginTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/registerAsUser", ReplyAction="http://tempuri.org/IMDB/registerAsUserResponse")]
        System.Threading.Tasks.Task registerAsUserAsync(long usrId, string userName, string firstName, string lastName, string joinDate, string passWord, string eMail, string lastLoginTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/login", ReplyAction="http://tempuri.org/IMDB/loginResponse")]
        bool login(string userName, string passWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/login", ReplyAction="http://tempuri.org/IMDB/loginResponse")]
        System.Threading.Tasks.Task<bool> loginAsync(string userName, string passWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/showUserId", ReplyAction="http://tempuri.org/IMDB/showUserIdResponse")]
        long showUserId(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/showUserId", ReplyAction="http://tempuri.org/IMDB/showUserIdResponse")]
        System.Threading.Tasks.Task<long> showUserIdAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/showUserName", ReplyAction="http://tempuri.org/IMDB/showUserNameResponse")]
        string showUserName(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/showUserName", ReplyAction="http://tempuri.org/IMDB/showUserNameResponse")]
        System.Threading.Tasks.Task<string> showUserNameAsync(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/showEmail", ReplyAction="http://tempuri.org/IMDB/showEmailResponse")]
        string showEmail(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/showEmail", ReplyAction="http://tempuri.org/IMDB/showEmailResponse")]
        System.Threading.Tasks.Task<string> showEmailAsync(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/checkUserName", ReplyAction="http://tempuri.org/IMDB/checkUserNameResponse")]
        bool checkUserName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/checkUserName", ReplyAction="http://tempuri.org/IMDB/checkUserNameResponse")]
        System.Threading.Tasks.Task<bool> checkUserNameAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/changePass", ReplyAction="http://tempuri.org/IMDB/changePassResponse")]
        bool changePass(long userId, string newPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/changePass", ReplyAction="http://tempuri.org/IMDB/changePassResponse")]
        System.Threading.Tasks.Task<bool> changePassAsync(long userId, string newPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/updateLoginTime", ReplyAction="http://tempuri.org/IMDB/updateLoginTimeResponse")]
        void updateLoginTime(long userId, string loginTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/updateLoginTime", ReplyAction="http://tempuri.org/IMDB/updateLoginTimeResponse")]
        System.Threading.Tasks.Task updateLoginTimeAsync(long userId, string loginTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/showBalance", ReplyAction="http://tempuri.org/IMDB/showBalanceResponse")]
        decimal showBalance(long userId, string coinType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMDB/showBalance", ReplyAction="http://tempuri.org/IMDB/showBalanceResponse")]
        System.Threading.Tasks.Task<decimal> showBalanceAsync(long userId, string coinType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMDBChannel : DatabaseHUB.ServiceReferenceMDB.IMDB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MDBClient : System.ServiceModel.ClientBase<DatabaseHUB.ServiceReferenceMDB.IMDB>, DatabaseHUB.ServiceReferenceMDB.IMDB {
        
        public MDBClient() {
        }
        
        public MDBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MDBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MDBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MDBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long getLastestExistedUserId() {
            return base.Channel.getLastestExistedUserId();
        }
        
        public System.Threading.Tasks.Task<long> getLastestExistedUserIdAsync() {
            return base.Channel.getLastestExistedUserIdAsync();
        }
        
        public void registerAsUser(long usrId, string userName, string firstName, string lastName, string joinDate, string passWord, string eMail, string lastLoginTime) {
            base.Channel.registerAsUser(usrId, userName, firstName, lastName, joinDate, passWord, eMail, lastLoginTime);
        }
        
        public System.Threading.Tasks.Task registerAsUserAsync(long usrId, string userName, string firstName, string lastName, string joinDate, string passWord, string eMail, string lastLoginTime) {
            return base.Channel.registerAsUserAsync(usrId, userName, firstName, lastName, joinDate, passWord, eMail, lastLoginTime);
        }
        
        public bool login(string userName, string passWord) {
            return base.Channel.login(userName, passWord);
        }
        
        public System.Threading.Tasks.Task<bool> loginAsync(string userName, string passWord) {
            return base.Channel.loginAsync(userName, passWord);
        }
        
        public long showUserId(string userName) {
            return base.Channel.showUserId(userName);
        }
        
        public System.Threading.Tasks.Task<long> showUserIdAsync(string userName) {
            return base.Channel.showUserIdAsync(userName);
        }
        
        public string showUserName(long userId) {
            return base.Channel.showUserName(userId);
        }
        
        public System.Threading.Tasks.Task<string> showUserNameAsync(long userId) {
            return base.Channel.showUserNameAsync(userId);
        }
        
        public string showEmail(long userId) {
            return base.Channel.showEmail(userId);
        }
        
        public System.Threading.Tasks.Task<string> showEmailAsync(long userId) {
            return base.Channel.showEmailAsync(userId);
        }
        
        public bool checkUserName(string userName) {
            return base.Channel.checkUserName(userName);
        }
        
        public System.Threading.Tasks.Task<bool> checkUserNameAsync(string userName) {
            return base.Channel.checkUserNameAsync(userName);
        }
        
        public bool changePass(long userId, string newPass) {
            return base.Channel.changePass(userId, newPass);
        }
        
        public System.Threading.Tasks.Task<bool> changePassAsync(long userId, string newPass) {
            return base.Channel.changePassAsync(userId, newPass);
        }
        
        public void updateLoginTime(long userId, string loginTime) {
            base.Channel.updateLoginTime(userId, loginTime);
        }
        
        public System.Threading.Tasks.Task updateLoginTimeAsync(long userId, string loginTime) {
            return base.Channel.updateLoginTimeAsync(userId, loginTime);
        }
        
        public decimal showBalance(long userId, string coinType) {
            return base.Channel.showBalance(userId, coinType);
        }
        
        public System.Threading.Tasks.Task<decimal> showBalanceAsync(long userId, string coinType) {
            return base.Channel.showBalanceAsync(userId, coinType);
        }
    }
}
